services:
  document-python:
    build: 
      context: './python/'
    container_name: document-llm
    networks:
      - document-llm-network
    ports:
      - "8501:8501"  
    volumes:
      - ${DOCAPPPATH}:/app
      - documentllmdb:/root/.cache/pypoetry/virtualenvs
    # command: poetry run streamlit run doc_app.py
    command: tail -f /dev/null
    extra_hosts:
      - "host.docker.internal:host-gateway"              
networks:
  document-llm-network:
    ipam:
      driver: default
volumes:
  documentllmdb:
    external: true 

