services:
  document-python:
    build: 
      context: './python/'
    container_name: document-llm
    networks:
      - document-llm-network
    volumes:
      - ${DOCAPPPATH}:/app
    command: tail -f /dev/null   
  ollama:
    build: 
      context: './ollama/'
    container_name: ollama
    networks:
      - document-llm-network
    volumes:
      - ${DOCAPPPATH}:/data             
networks:
  document-llm-network:
    ipam:
      driver: default


