services:
  document-python:
    build: 
      context: './python/'
    container_name: document-llm
    networks:
      - document-llm-network
    volumes:
      - ${DOCAPPPATH}:/app
    command: tail -f /dev/null               
networks:
  document-llm-network:
    ipam:
      driver: default
# volumes:
#   ollamadb:
#     external: true 

