services:
  document-python:
    build: 
      context: './python/'
    container_name: document-llm
    networks:
      - document-llm-network
    volumes:
      - ${DOCAPPPATH}:/app
      - documentllmdb:/root/.cache/pypoetry/virtualenvs
    command: tail -f /dev/null               
networks:
  document-llm-network:
    ipam:
      driver: default
volumes:
  documentllmdb:
    external: true 

